name: Testing and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: ['lint', 'test']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        if: ${{ matrix.job == 'lint' }}
        run: npm run lint

      - name: Run tests
        if: ${{ matrix.job == 'test' }}
        run: npm run test

  check-status:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Check status
        run: |
          if [ ${{ needs.lint-and-test.outputs.lint_success }} == 'false' ]; then
            echo "Linter failed!"
            exit 1
          fi
          if [ ${{ needs.lint-and-test.outputs.test_success }} == 'false' ]; then
            echo "Tests failed!"
            exit 1
          fi
        env:
          LINT_SUCCESS: ${{ needs.lint-and-test.outputs.lint_success }}
          TEST_SUCCESS: ${{ needs.lint-and-test.outputs.test_success }}

      - name: Set merge restrictions
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              body: 'Changes cannot be merged as linter or tests failed!'
            })
